---
title: promise初识
date: 2022-01-21 00:00:00
sidebar: auto
sticky: false
permalink: /pages/promise211021/
categories:
  - 技术
tags:
  - promise
---

<p align="center">
  <img width="500" src="https://p18.qhimg.com/dmfd/2560_1440_/t0120fcf2ecc6026634.jpg"/>
</p>


> 待完善，感谢指教 🌹🌹🌹
>
> <!-- more -->

## promise初识

- 回调函数分类

  - 同步回调

    理解： 立即执行，完全执行完了才结束，不会放入回调队列中

    例子： 数组遍历

  - 异步回调

    理解：不会立即执行，会放入回调队列中来执行

    例子：定时器回调 / ajax回调 / Promise的成功 | 失败的回调

- error分类

  - 错误的类型

    1. Error: 所有错误的父类型
  
    2. ReferenceError:  引用的变量不存在
  
    3. TypeError: 数据类型不正确

    4. RangeError: 数据值不在其所允许的范围内

    5. SyntaxError: 语法错误

    6. URLError： URL相关函数的参数不正确抛出的错误

    7. EvalError： eval函数没有被正确执行时

    8. **[`InternalError`](https://developer.mozilla.org/zh-CN/docs/Web/JavaScript/Reference/Global_Objects/InternalError)** ：引擎报错

       ```javascript
       eveal() 函数
       将字符串转为 js 语句 执行
       
       // 案例
       eval("x=10;y=20;document.write(x*y)");
       document.write("<br>" + eval("2+2"));
       document.write("<br>" + eval(x+17));
       
       // 结果
       200
       4
       27
       ```
  
       ![img](https://staticqn.qizuang.com/custom/20220517/FjC0R2QoLF2DMfZilJGAJcDcJmKb)
  
  - 错误处理
  
    捕获错误： try ... catch
  
    抛出错误： throw error
  
    > [如果将 throw 与 try 和catch 一起使用， 那么您能够控制程序流， 并生成**自定义的错误消息**](https://www.runoob.com/try/try.php?filename=tryjs_throw_error)
  
  - 错误对象 
  
    message属性： 错误相关信息
  
    stack属性： 函数调用栈记录信息

- 为什么要用Promise

  1. 指定回调函数的方式更加灵活

     - 旧的： 必须在启动异步任务前
     - promise: 启动异步任务 =》 返回promise对象 =》给promise对象绑定回调函数（甚至可以在异步任务结束后指定）

  2. 支持链式调用，可以解决回调地狱问题

     - 什么是回调地狱？

       > 标志： **嵌套**，callback
       >
       >  回调函数**嵌套**调用，外部回调函数异步执行的结果是嵌套的回调函数执行的条件

     - 回调函数的缺点？ 不便于阅读 / 不便于异常处理

     - 解决方案？ promise链式调用

       > then的返回依旧还是promise对象，轻松解决

       ```
       const p = new Promise((resolve, reject)=>{})
       p.then(value=>{},reason=>{}).then().then() ...
       ```

     - 终极解决方案？ async / await

       ```javascript
       async function request() {
       	try {
       		const result = await doSomething()
       		const newResult = await doSomethingElse(result)
       		const finalResult = await doThirdThing(new Result)
       		console.log('result:'+ finalResult)
       	} catch(error) {
       		failureCallback(error)
       	}
       }
       ```

- PromiseAPI

  ![img](https://staticqn.qizuang.com/custom/20220517/Fu_bXAff3RkJe3AWZI6KG5Lpamnp)

  1. Promise构造函数

     ```javascript
     构造函数 Promise (excutor) {}
     excutor 函数： 同步执行 (resolve, reject) => {}
     resolve 函数： 内部定义成功时我们调用的函数 value => {}
     reject 函数： 内部定义失败时我们调用的函数 reason => {}
     ```

     > 说明： excutor 会在Promise**内部**立即**同步**回调，**异步**操作在执行器**中**执行

  2. Promise.prototype.then 方法

     ```
     (onResolved, onRejected) => {
     	onResolved函数： 成功的回调函数 (value) => {}
     	onRejected函数： 失败的回调函数 (reason) => {}
     	说明： 指定用于得到成功value的成功回调和用于得到失败reason的失败回调返回一个新的promise对象
     }
     ```

  3. Promise.prototype.catch方法

     ```
     (onRejected) => {
     	onRejected函数： 失败的回调函数(reason) => {
     		说明： then()的语法糖，相当于： then(undefined, onRejected)
     	}
     }
     ```

  4. Promise.resolve 方法

     ```
     (value) => {
     	value: 成功的数据或promise对象
     	说明： 返回一个成功 / 失败的promise 对象
     }
     ```

  5. Promise.reject 方法

     ```
     (reason) => {
     	reason: 失败的原因
     	说明： 返回一个失败的 promise 对象
     }
     ```

  6. Promise.all 方法

     > 返回数组， 结果集合

     ```
     (promises) = >{}
     promises: 包括n个pormsie 的数组
     说明： 返回一个新的promsie， 只有所有的promise都成功才成功， 只要有一个失败就直接失败
     
     // 结果
     ['p1', 'p2']
     ```

  7. Promise.allSettled 方法

     > 返回对象

     ```javascript
     let p1 = new Promise((resolve, reject) => {
         setTimeout(()=>{
             resolve('p1');
         },500)
     })
     let p2 = new Promise((resolve, reject) => {
         setTimeout(()=>{
             resolve('p2');
         },1000)
     })
     let p = Promise.allSettled([p1, p2]).then(res=>{
         console.log(res);
     })
     
     // 结果
     {
     	[status: 'fulfilled', value: 'p1'],
     	[status: 'fulfilled', vlaue: 'p2']
     }
     ```

  8. Promsie.race方法

     ```
     (promise) => {
     	Promises: 包含n个promsie 的数组
     	说明： 返回一个新的promise，第一个完成的promise的结果状态就是最终的结果状态
     }
     ```

- 如何改变Promise 的状态

  1. resolve（value）: 如果当前是pendding 就会变成 resolved
  2. reject（reason）：如果当前是pendding 就会变为 rejected
  3. 抛出异常： 如果当前是 pendding 就会变为rejected

- 一个promise指定多个成功 / 失败回调函数， 都会调用吗？ 

  当promise 改变对应状态时都会调用

- 改变promise 状态和指定回调函数谁先谁后？

  1. 都有可能，正常情况下是先指定回调再改变状态，但也可以先改变状态再指定回调
  2. 如何先改状态再指定回调
     - 执行器中直接调动 resolve() / reject()
     - 延迟更长时间才调用 then（）
  3. 什么时候才能得到数据
     - 如果先指定的回调， 那当状态发生改变时，回调函数就会调用，得到数据
     - 如果先改变状态，那当指定回调时，回调函数就会调用， 得到数据

- promise.then() 返回的新promise 的结果状态由什么决定?

  - 简单表达： 由then（）指定的回调函数执行的结果决定

  - **详细表达**

    1. 如果抛出异常， 新promise 变为 rejected， reason为 抛出的异常

    2. 如果返回的是非promise 的任意值，新promise 变为 resolved, value 为返回的值

    3. 如果返回的是另一个新 promise， 此promise的结果 就会成为新promise的结果

       ![img](https://staticqn.qizuang.com/custom/20220517/Frthj1p7J5eNzxKvzlFoHxlfll1Y)

- promise 如何串联多个操作任务

  1. promise 的then（） 返回一个新的promise, 可以开成 then（）的链式调用
  2. 通过 then的链式调用串联多个同步 / 异步任务

- promise **异常穿透**

  - 场景

    当时用promise 的then 链式调用时，可以在最后指定失败的回调

  - 实现

    前面任何操作出了异常，都会传到最后失败的回调中处理

- 中断promise链

  > 在回调函数中返回一个 pedding状态的 promise对象

  ```
  new Promise ((reject, reject) => {
  	reject(1)
  }).then().then().then(
  	return new Promsie(() => {})
  )
  ```

## 自定义（手写）Promise

```javascript
(function (window){
    function Promise(excutor) {
        const self = this
        // 初始化
        self.status = "pending"
        self.data = undefined
        self.callbacks = []
        function resolve(value) {
            if(self.status !== 'pending') {
                return
            }
            self.status = 'resolved'
            self.data = value
            if(self.callbacks.length>0){
                setTimeout(() => {
                    self.callbacks.forEach(obj => {
                        obj.onResolved(value)
                    })
                })
            }
        }
        function reject(reason) {
            if(self.status !== 'pending') {
                return
            }
            self.staus = 'rejected'
            self.data = reason
            setTimeout(() => {
                obj.onRejected(reason)
            })
        }
        try {
            excutor(resolve, reject)
        } catch (error) {
            reject(error)
        }
        
        // then
        Promise.prototype.then = function (onResolved, onRejected) {
            const self = this
            onResolved = typeof onResolved === 'function' ? onResolved : value =>value
            onRejected = typeof onRejected === 'function' ? onRejected : reason => {throw reason}
            return new Promise ((resolve, reject) => {
                function handle(callback) {
                    try {
                        const x = callback(self.data)
                        if(x instanceof Promise) {
                            x.then(resolve, reject)
                        } else {
                            resolve(x)
                        }
                    } catch (error) {
                        reject(error)
                    }
                }
                if(self.status === 'resolved') {
                    setTimeout(() => {
                        handle(onResolved)
                    })
                } else if (self.status === 'rejected') {
                    setTimeout(() => {
                        handle(onRejected)
                    })
                } else {
                    self.callbacks.push({
                        onResolved(value) {
                            handle(onResolved)
                        },
                        onRejected(reason) {
                            handle(onRejected)
                        }
                    })
                }
            })
        }
        
        // catch
        Promise.prototype.catch = function (onRejected) {
            return this.then(null, onRejected)
        }
        
        // resolve
        Promise.resolve = function(value) {
            return new Promise((resolve, reject) => {
                if(value instanceof Promise) {
                    value.then(resolve, reject)
                } else {
                    resolve(value)
                }
            })
        }
        
        // reject
        Promise.reject = function(reason) {
            return new Promise((resolve, reject) => {
                reject(reason)
            })
        }
        
        // all
        Promise.all = function(promises) {
            return new Promise((resolve, reject) => {
                let resolvedCount = 0
                const promisesLength = promises.length
                const values = new Array(promisesLength)
                for(let i=0; i<promisesLength; i++) {
                    Promise.resolve(promises[i]).then(
                    	value => {
                            values[i] = value
                            resolvedCount ++
                            if(resolvedCount === promisesLength) {
                                resolve(values)
                            }
                        },
                        reason => {
                            reject(reason)
                        }
                    )
                }
            })
        }
        
        // race
        Promise.race = function(promises) {
            return new Promise((resonlve, reject) => {
                for(let i=0; i<promises.length; i++) {
                    Promsie.resolve(promises[i]).then(
                    	(value) => {
                            resolve(value)
                        },
                        (reason) => {
                            reject(reason)
                        }
                    )
                }
            })
        }
    }
})
```

## async 与 await

- async 函数

  - 函数的返回值为promise对象
  - promise对象的结果由 async 函数执行的返回值决定

  ![img](https://staticqn.qizuang.com/custom/20220517/FgmvtKPLuFhWyBQUOZjYbh8in1wx)

- await 表达式

  - await 右侧的表达式一般为promise 对象， 但也可以是别的值
  - 如果表达式是promise对象，await 返回的是promise成功的值
  - 如果表达式是其他值，直接将此值作为await的返回值

- 注意

  - await 必须写在 async 函数中，但 async 函数中可以没有 await
  - 如果 await 的promise失败了， 就会抛出异常，需要通过 try...catch 捕获处理
  - 多个await 可以用一个catch接收， **异常穿透**在这里也好使

## JS异步 宏队列 / 微队列

1. JS中用来存储待执行回调函数的队列包含 2个 不同特定的列队

2. 宏队列

   - 定时器回调
   - DOM事件回调
   - ajax 回调
   - 文件操作

3. 微队列

   - promise的回调
   - MutationObserver 监听DOM对象的变化 

4. js执行时会区别这2个队列

   - js引擎首先必须先执行所有的初始化同步任务代码

   - 每次准备取出第一个宏任务执行前，都要将所有的微任务一个一个取出来执行

     ![img](https://staticqn.qizuang.com/custom/20220517/Fh3j7rgJrqloUHmYbW4UUiFfkhib)

5. [案例](https://www.jianshu.com/p/334b0e40b4dd)

